# Generated by Django 4.2 on 2023-05-01 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_buyer_purchase_date_alter_seller_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 1, 1, 16, 40, 959992, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='seller',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 1, 1, 16, 40, 959253, tzinfo=datetime.timezone.utc)),
        ),
    ]
