# Generated by Django 4.2 on 2023-05-01 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_buyer_purchase_date_alter_seller_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 1, 1, 22, 6, 870652, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='seller',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 1, 1, 22, 6, 869948, tzinfo=datetime.timezone.utc)),
        ),
    ]
