# Generated by Django 4.2 on 2023-05-02 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_buyer_purchase_date_alter_seller_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 2, 5, 8, 24, 373569, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='seller',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 5, 8, 24, 372793, tzinfo=datetime.timezone.utc)),
        ),
    ]
