# Generated by Django 4.2 on 2023-05-06 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_buyer_purchase_date_alter_seller_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 6, 15, 41, 20, 794802, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='seller',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 15, 41, 20, 793974, tzinfo=datetime.timezone.utc)),
        ),
    ]
