# Generated by Django 4.2 on 2023-05-06 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_buyer_purchase_date_alter_seller_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 6, 18, 43, 54, 521259, tzinfo=datetime.timezone.utc)),
        ),
    ]
