# Generated by Django 4.2 on 2023-05-06 19:48

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_seller_date_alter_buyer_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 6, 19, 48, 29, 209771, tzinfo=datetime.timezone.utc)),
        ),
    ]
