# Generated by Django 4.2 on 2023-05-07 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_buyer_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 7, 20, 17, 18, 635936, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='producat',
            name='img',
            field=models.ImageField(upload_to='media/media'),
        ),
    ]
